'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace WS_Porkys
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WS_Porkys.WS_PorkysSoap")>  _
    Public Interface WS_PorkysSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Sql_Get", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Sql_Get(ByVal query As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Sql_Set", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Sql_Set(ByVal query As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Sql_Get_Value", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Sql_Get_Value(ByVal query As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WS_PorkysSoapChannel
        Inherits WS_Porkys.WS_PorkysSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WS_PorkysSoapClient
        Inherits System.ServiceModel.ClientBase(Of WS_Porkys.WS_PorkysSoap)
        Implements WS_Porkys.WS_PorkysSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Sql_Get(ByVal query As String) As System.Data.DataSet Implements WS_Porkys.WS_PorkysSoap.Sql_Get
            Return MyBase.Channel.Sql_Get(query)
        End Function
        
        Public Function Sql_Set(ByVal query As String) As String Implements WS_Porkys.WS_PorkysSoap.Sql_Set
            Return MyBase.Channel.Sql_Set(query)
        End Function
        
        Public Function Sql_Get_Value(ByVal query As String) As String Implements WS_Porkys.WS_PorkysSoap.Sql_Get_Value
            Return MyBase.Channel.Sql_Get_Value(query)
        End Function
    End Class
End Namespace
