'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PORKYS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Acercade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Acercade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Public ReadOnly Property alert() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("alert", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ArchivoExcel_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchivoExcel_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ArchivoExcel_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArchivoExcel_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property boton_nuevo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton_nuevo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CandadoAbierto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CandadoAbierto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CandadoCerrado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CandadoCerrado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property cheques() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cheques", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CotizacionMoneda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CotizacionMoneda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property empleados() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("empleados", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property excel_noticia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel_noticia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Factura() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Factura", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Factura1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Factura1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property fmaic_printorganizer_save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fmaic_printorganizer_save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FondodePantalla() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondodePantalla", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FondodePantalla_blanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondodePantalla_blanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FondodePantalla_mit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondodePantalla_mit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FondodePantalla_mit1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondodePantalla_mit1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Gastos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gastos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Green_Ball_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Green_Ball_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icono_ayuda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icono_ayuda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icono_guardar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icono_guardar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property indicator_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("indicator_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ListaPrecios() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ListaPrecios", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property logo_MIT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_MIT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property logo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Microsoft_Word_2013_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_Word_2013_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ms_excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ms_excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property nuevo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nuevo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Public ReadOnly Property ok() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ok", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Orden_de_Compra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Orden_de_Compra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Pagos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pagos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PendienteAmarillo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PendienteAmarillo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PendienteRojo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PendienteRojo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PendienteVerde2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PendienteVerde2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Public ReadOnly Property Porkys() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Porkys", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Public ReadOnly Property PorkysU() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PorkysU", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Presentacion3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Presentacion3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Presupuestos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Presupuestos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Presupuestos1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Presupuestos1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Presupuestos2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Presupuestos2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Productos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Productos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Productos1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Productos1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PtoVtaPorkys() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PtoVtaPorkys", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Red_Ball_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Red_Ball_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Remito() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Remito", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Remito1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Remito1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Sincro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sincro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SincroBalanzas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SincroBalanzas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SincroFALLA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SincroFALLA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SincroOK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SincroOK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SincroPendiente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SincroPendiente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Public ReadOnly Property stop_error() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("stop_error", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Symbol_Check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Symbol_Check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property users() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Ventas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ventas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Ventas16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ventas16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Word() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Word", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property word2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("word2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
